/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Conta;

/**
 *
 * @author iuryi
 */
public class JF4DeletaCliente extends javax.swing.JFrame {

    ArrayList<Cliente> ListaCliente;
    ArrayList<Conta> Contas;
    Cliente deletaCliente;

    /**
     * Creates new form JFDeletaCliente2
     */
    public void CarregaTabelaCliente() {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"CPF", "Nome", "Sexo", "Data de Nascimento", "Endereço"}, 0);
        for (int i = 0; i < ListaCliente.size(); i++) {
            modelo.addRow(new Object[]{ListaCliente.get(i).getCPF(), ListaCliente.get(i).getNome(), ListaCliente.get(i).getSexo(), ListaCliente.get(i).getDataNascimento(), ListaCliente.get(i).getEndereco()});
        }
        TableSelecionaCliente.setModel(modelo);
    }

    public JF4DeletaCliente(ArrayList<Cliente> ListaCliente, ArrayList<Conta> Contas) {
        this.ListaCliente = ListaCliente;
        this.Contas = Contas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSelecionaCliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSelecionaCliente = new javax.swing.JTable();
        jButtonDeletaCliente = new javax.swing.JButton();
        jButtonCancelarDeletaCliente = new javax.swing.JButton();
        ButtonListarClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSelecionaCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione Cliente"));

        TableSelecionaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Sexo", "Data Nascimento", "Endereço"
            }
        ));
        TableSelecionaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSelecionaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSelecionaCliente);

        javax.swing.GroupLayout jPanelSelecionaClienteLayout = new javax.swing.GroupLayout(jPanelSelecionaCliente);
        jPanelSelecionaCliente.setLayout(jPanelSelecionaClienteLayout);
        jPanelSelecionaClienteLayout.setHorizontalGroup(
            jPanelSelecionaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSelecionaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSelecionaClienteLayout.setVerticalGroup(
            jPanelSelecionaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSelecionaClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        jButtonDeletaCliente.setText("Deleta");
        jButtonDeletaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletaClienteActionPerformed(evt);
            }
        });

        jButtonCancelarDeletaCliente.setText("Cancelar");
        jButtonCancelarDeletaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarDeletaClienteActionPerformed(evt);
            }
        });

        ButtonListarClientes.setText("Listar Clientes");
        ButtonListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSelecionaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDeletaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarDeletaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonListarClientes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonListarClientes)
                .addGap(5, 5, 5)
                .addComponent(jPanelSelecionaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeletaCliente)
                    .addComponent(jButtonCancelarDeletaCliente))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableSelecionaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSelecionaClienteMouseClicked
        // TODO add your handling code here:
        TableSelecionaCliente.getValueAt(TableSelecionaCliente.getSelectedRow(), 0);
    }//GEN-LAST:event_TableSelecionaClienteMouseClicked

    private void jButtonDeletaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletaClienteActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < ListaCliente.size(); i++) {
            if (TableSelecionaCliente.getValueAt(TableSelecionaCliente.getSelectedRow(), 0).equals(ListaCliente.get(i).getCPF())) {
                deletaCliente = ListaCliente.get(i);
                break;
            }
        }
        ListaCliente.remove(deletaCliente);
        CarregaTabelaCliente();
        JOptionPane.showMessageDialog(rootPane, "Dados deletados com sucesso.");
    }//GEN-LAST:event_jButtonDeletaClienteActionPerformed

    private void jButtonCancelarDeletaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarDeletaClienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarDeletaClienteActionPerformed

    private void ButtonListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListarClientesActionPerformed
        // TODO add your handling code here:
        CarregaTabelaCliente();
    }//GEN-LAST:event_ButtonListarClientesActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFDeletaCliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFDeletaCliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFDeletaCliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFDeletaCliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFDeletaCliente2().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonListarClientes;
    private javax.swing.JTable TableSelecionaCliente;
    private javax.swing.JButton jButtonCancelarDeletaCliente;
    private javax.swing.JButton jButtonDeletaCliente;
    private javax.swing.JPanel jPanelSelecionaCliente;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
