/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Conta;

/**
 *
 * @author iuryi
 */
public class JF6AtualizaConta extends javax.swing.JFrame {

    ArrayList<Cliente> ListaCliente;
    ArrayList<Conta> Contas;
    Cliente clienteAtualizaConta;
    Conta ContaAtualiza;
    double novoSaldo;
    int nContaAtualiza;

    /**
     * Creates new form JFAtualizaConta
     */
    public void CarregaTabelaCliente() {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"CPF", "Nome", "Sexo", "Data de Nascimento", "Endereço"}, 0);
        for (int i = 0; i < ListaCliente.size(); i++) {
            modelo.addRow(new Object[]{ListaCliente.get(i).getCPF(),
                ListaCliente.get(i).getNome(),
                ListaCliente.get(i).getSexo(),
                ListaCliente.get(i).getDataNascimento(),
                ListaCliente.get(i).getEndereco()});
        }
        TableSelecionaClienteAtualizaConta.setModel(modelo);
    }

    public void CarregaTabelaConta() {
        ArrayList<Conta> relatorioConta = clienteAtualizaConta.getContas();
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Conta", "Numero", "Saldo"}, 0);
        for (int i = 0; i < relatorioConta.size(); i++) {
            modelo.addRow(new Object[]{relatorioConta.get(i).getTipo(),
                relatorioConta.get(i).getNumero(),
                relatorioConta.get(i).getSaldo()});
            TableSelecionaContaAtualizaConta.setModel(modelo);
        }
    }

    public JF6AtualizaConta(ArrayList<Cliente> ListaCliente, ArrayList<Conta> Contas) {
        initComponents();
        //   this.CarregaTabelaCliente();
        this.ListaCliente = ListaCliente;
        this.Contas = Contas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSelecionaClienteAtualizaConta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSelecionaClienteAtualizaConta = new javax.swing.JTable();
        PanelSelecionaContaAtualizaConta = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableSelecionaContaAtualizaConta = new javax.swing.JTable();
        ButtonAtualizaConta = new javax.swing.JButton();
        ButtonCancelaAtualizaConta = new javax.swing.JButton();
        LabelSaldoContaAtualizaConta = new javax.swing.JLabel();
        TextFieldAlteraSaldoContaAtualizarConta = new javax.swing.JTextField();
        ButtonListarClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelSelecionaClienteAtualizaConta.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione o Cliente"));

        TableSelecionaClienteAtualizaConta.setAutoCreateRowSorter(true);
        TableSelecionaClienteAtualizaConta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Sexo", "Data de Nascimento", "Endereço"
            }
        ));
        TableSelecionaClienteAtualizaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSelecionaClienteAtualizaContaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSelecionaClienteAtualizaConta);

        PanelSelecionaContaAtualizaConta.setBorder(javax.swing.BorderFactory.createTitledBorder("Contas do Cliente"));

        TableSelecionaContaAtualizaConta.setAutoCreateRowSorter(true);
        TableSelecionaContaAtualizaConta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Conta", "N° da Conta", "Saldo da Conta"
            }
        ));
        TableSelecionaContaAtualizaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSelecionaContaAtualizaContaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableSelecionaContaAtualizaConta);

        javax.swing.GroupLayout PanelSelecionaContaAtualizaContaLayout = new javax.swing.GroupLayout(PanelSelecionaContaAtualizaConta);
        PanelSelecionaContaAtualizaConta.setLayout(PanelSelecionaContaAtualizaContaLayout);
        PanelSelecionaContaAtualizaContaLayout.setHorizontalGroup(
            PanelSelecionaContaAtualizaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelecionaContaAtualizaContaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSelecionaContaAtualizaContaLayout.setVerticalGroup(
            PanelSelecionaContaAtualizaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelecionaContaAtualizaContaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelSelecionaClienteAtualizaContaLayout = new javax.swing.GroupLayout(PanelSelecionaClienteAtualizaConta);
        PanelSelecionaClienteAtualizaConta.setLayout(PanelSelecionaClienteAtualizaContaLayout);
        PanelSelecionaClienteAtualizaContaLayout.setHorizontalGroup(
            PanelSelecionaClienteAtualizaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelecionaClienteAtualizaContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSelecionaClienteAtualizaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(PanelSelecionaContaAtualizaConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelSelecionaClienteAtualizaContaLayout.setVerticalGroup(
            PanelSelecionaClienteAtualizaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelecionaClienteAtualizaContaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelSelecionaContaAtualizaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonAtualizaConta.setText("Atualizar");
        ButtonAtualizaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAtualizaContaActionPerformed(evt);
            }
        });

        ButtonCancelaAtualizaConta.setText("Cancelar");
        ButtonCancelaAtualizaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelaAtualizaContaActionPerformed(evt);
            }
        });

        LabelSaldoContaAtualizaConta.setText("Saldo da Conta:");

        TextFieldAlteraSaldoContaAtualizarConta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldAlteraSaldoContaAtualizarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAlteraSaldoContaAtualizarContaActionPerformed(evt);
            }
        });

        ButtonListarClientes.setText("Listar Clientes");
        ButtonListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelSelecionaClienteAtualizaConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonListarClientes)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelSaldoContaAtualizaConta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldAlteraSaldoContaAtualizarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonAtualizaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonCancelaAtualizaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonListarClientes)
                .addGap(18, 18, 18)
                .addComponent(PanelSelecionaClienteAtualizaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSaldoContaAtualizaConta)
                    .addComponent(TextFieldAlteraSaldoContaAtualizarConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAtualizaConta)
                    .addComponent(ButtonCancelaAtualizaConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableSelecionaClienteAtualizaContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSelecionaClienteAtualizaContaMouseClicked
        // TODO add your handling code here:
        TableSelecionaClienteAtualizaConta.getValueAt(TableSelecionaClienteAtualizaConta.getSelectedRow(), 0);
        for (int i = 0; i < ListaCliente.size(); i++) {
            if (TableSelecionaClienteAtualizaConta.getValueAt(TableSelecionaClienteAtualizaConta.getSelectedRow(), 0).equals(ListaCliente.get(i).getCPF())) {
                clienteAtualizaConta = ListaCliente.get(i);
                CarregaTabelaConta();
                break;
            }
        }
    }//GEN-LAST:event_TableSelecionaClienteAtualizaContaMouseClicked

    private void TableSelecionaContaAtualizaContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSelecionaContaAtualizaContaMouseClicked
        // TODO add your handling code here:

        nContaAtualiza = Integer.parseInt(TableSelecionaContaAtualizaConta.getValueAt(TableSelecionaContaAtualizaConta.getSelectedRow(), 1).toString());
        TableSelecionaContaAtualizaConta.getValueAt(TableSelecionaContaAtualizaConta.getSelectedRow(), 1);
        for (int i = 0; i < clienteAtualizaConta.getContas().size(); i++) {
            if (nContaAtualiza == Contas.get(i).getNumero()) {
                ContaAtualiza = clienteAtualizaConta.getContas().get(i);
                break;
            }
        }
    }//GEN-LAST:event_TableSelecionaContaAtualizaContaMouseClicked

    private void ButtonAtualizaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAtualizaContaActionPerformed
        // TODO add your handling code here:
        novoSaldo = Double.parseDouble(TextFieldAlteraSaldoContaAtualizarConta.getText());
        ContaAtualiza.setSaldo(novoSaldo);
        TextFieldAlteraSaldoContaAtualizarConta.setText("");
        JOptionPane.showMessageDialog(rootPane, "Saldo atualizado com sucesso.");
        CarregaTabelaConta();
    }//GEN-LAST:event_ButtonAtualizaContaActionPerformed

    private void ButtonCancelaAtualizaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelaAtualizaContaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonCancelaAtualizaContaActionPerformed

    private void TextFieldAlteraSaldoContaAtualizarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAlteraSaldoContaAtualizarContaActionPerformed
        // TODO add your handling code here:
        TextFieldAlteraSaldoContaAtualizarConta.getText();
    }//GEN-LAST:event_TextFieldAlteraSaldoContaAtualizarContaActionPerformed

    private void ButtonListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListarClientesActionPerformed
        // TODO add your handling code here:
        CarregaTabelaCliente();
    }//GEN-LAST:event_ButtonListarClientesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAtualizaConta;
    private javax.swing.JButton ButtonCancelaAtualizaConta;
    private javax.swing.JButton ButtonListarClientes;
    private javax.swing.JLabel LabelSaldoContaAtualizaConta;
    private javax.swing.JPanel PanelSelecionaClienteAtualizaConta;
    private javax.swing.JPanel PanelSelecionaContaAtualizaConta;
    private javax.swing.JTable TableSelecionaClienteAtualizaConta;
    private javax.swing.JTable TableSelecionaContaAtualizaConta;
    private javax.swing.JTextField TextFieldAlteraSaldoContaAtualizarConta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
