/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Conta;

/**
 *
 * @author iuryi
 */
public class JF7DeletaConta extends javax.swing.JFrame {

    ArrayList<Cliente> ListaCliente;
    ArrayList<Conta> Contas;
    Cliente clienteDeletaConta;
    Conta ContaDeleta;
    int nContaAtualiza;

    /**
     * Creates new form JFDeletaConta
     */
    public void CarregaTabelaCliente() {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"CPF", "Nome", "Sexo", "Data de Nascimento", "Endereço"}, 0);
        for (int i = 0; i < ListaCliente.size(); i++) {
            modelo.addRow(new Object[]{ListaCliente.get(i).getCPF(), ListaCliente.get(i).getNome(), ListaCliente.get(i).getSexo(), ListaCliente.get(i).getDataNascimento(), ListaCliente.get(i).getEndereco()});
        }
        TableSelecionaClienteDeletaConta.setModel(modelo);
    }

    public void CarregaTabelaConta() {
        ArrayList<Conta> relatorioConta = clienteDeletaConta.getContas();
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Conta", "Numero", "Saldo"}, 0);
        for (int i = 0; i < relatorioConta.size(); i++) {
            modelo.addRow(new Object[]{relatorioConta.get(i).getTipo(),
                relatorioConta.get(i).getNumero(),
                relatorioConta.get(i).getSaldo()});
            TableSelecionaContaDeletaConta.setModel(modelo);
        }
    }

    public JF7DeletaConta(ArrayList<Cliente> ListaCliente, ArrayList<Conta> Contas) {
        this.ListaCliente = ListaCliente;
        this.Contas = Contas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSelecionaClienteDeletaConta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSelecionaClienteDeletaConta = new javax.swing.JTable();
        PanelContasClientesDeletaConta = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableSelecionaContaDeletaConta = new javax.swing.JTable();
        ButtonDeletaConta = new javax.swing.JButton();
        ButtonCancelaDeletaConta = new javax.swing.JButton();
        ButtonListarClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelSelecionaClienteDeletaConta.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione o Cliente"));

        TableSelecionaClienteDeletaConta.setAutoCreateRowSorter(true);
        TableSelecionaClienteDeletaConta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Sexo", "Data de Nascimento", "Endereço"
            }
        ));
        TableSelecionaClienteDeletaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSelecionaClienteDeletaContaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSelecionaClienteDeletaConta);

        PanelContasClientesDeletaConta.setBorder(javax.swing.BorderFactory.createTitledBorder("Contas do Cliente"));

        TableSelecionaContaDeletaConta.setAutoCreateRowSorter(true);
        TableSelecionaContaDeletaConta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Conta", "N° da Conta", "Saldo da Conta"
            }
        ));
        TableSelecionaContaDeletaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSelecionaContaDeletaContaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableSelecionaContaDeletaConta);

        javax.swing.GroupLayout PanelContasClientesDeletaContaLayout = new javax.swing.GroupLayout(PanelContasClientesDeletaConta);
        PanelContasClientesDeletaConta.setLayout(PanelContasClientesDeletaContaLayout);
        PanelContasClientesDeletaContaLayout.setHorizontalGroup(
            PanelContasClientesDeletaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContasClientesDeletaContaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelContasClientesDeletaContaLayout.setVerticalGroup(
            PanelContasClientesDeletaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContasClientesDeletaContaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelSelecionaClienteDeletaContaLayout = new javax.swing.GroupLayout(PanelSelecionaClienteDeletaConta);
        PanelSelecionaClienteDeletaConta.setLayout(PanelSelecionaClienteDeletaContaLayout);
        PanelSelecionaClienteDeletaContaLayout.setHorizontalGroup(
            PanelSelecionaClienteDeletaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelecionaClienteDeletaContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSelecionaClienteDeletaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                    .addComponent(PanelContasClientesDeletaConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelSelecionaClienteDeletaContaLayout.setVerticalGroup(
            PanelSelecionaClienteDeletaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelecionaClienteDeletaContaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelContasClientesDeletaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonDeletaConta.setText("Deletar");
        ButtonDeletaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeletaContaActionPerformed(evt);
            }
        });

        ButtonCancelaDeletaConta.setText("Cancelar");
        ButtonCancelaDeletaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelaDeletaContaActionPerformed(evt);
            }
        });

        ButtonListarClientes.setText("Listar Clientes");
        ButtonListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonDeletaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonCancelaDeletaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelSelecionaClienteDeletaConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonListarClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonListarClientes)
                .addGap(18, 18, 18)
                .addComponent(PanelSelecionaClienteDeletaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDeletaConta)
                    .addComponent(ButtonCancelaDeletaConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableSelecionaClienteDeletaContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSelecionaClienteDeletaContaMouseClicked
        // TODO add your handling code here:
        TableSelecionaClienteDeletaConta.getValueAt(TableSelecionaClienteDeletaConta.getSelectedRow(), 0);
        for (int i = 0; i < ListaCliente.size(); i++) {
            if (TableSelecionaClienteDeletaConta.getValueAt(TableSelecionaClienteDeletaConta.getSelectedRow(), 0).equals(ListaCliente.get(i).getCPF())) {
                clienteDeletaConta = ListaCliente.get(i);
                CarregaTabelaConta();
                break;
            }
        }
        // TableSelecionaClienteDeletaConta.getSelectedRow();
    }//GEN-LAST:event_TableSelecionaClienteDeletaContaMouseClicked

    private void TableSelecionaContaDeletaContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSelecionaContaDeletaContaMouseClicked
        // TODO add your handling code here:
        nContaAtualiza = Integer.parseInt(TableSelecionaContaDeletaConta.getValueAt(TableSelecionaContaDeletaConta.getSelectedRow(), 1).toString());
        TableSelecionaContaDeletaConta.getValueAt(TableSelecionaContaDeletaConta.getSelectedRow(), 1);
        for (int i = 0; i < clienteDeletaConta.getContas().size(); i++) {
            if (nContaAtualiza == Contas.get(i).getNumero()) {
                ContaDeleta = clienteDeletaConta.getContas().get(i);
                break;
            }
        }
    }//GEN-LAST:event_TableSelecionaContaDeletaContaMouseClicked

    private void ButtonDeletaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeletaContaActionPerformed
        // TODO add your handling code here:

        clienteDeletaConta.getContas().remove(ContaDeleta);
        JOptionPane.showMessageDialog(rootPane, "Conta deletada com sucesso.");
        CarregaTabelaConta();
        //  ((DefaultTableModel) TableSelecionaContaDeletaConta.getModel()).setRowCount(0);


    }//GEN-LAST:event_ButtonDeletaContaActionPerformed

    private void ButtonCancelaDeletaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelaDeletaContaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonCancelaDeletaContaActionPerformed

    private void ButtonListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListarClientesActionPerformed
        // TODO add your handling code here:
        CarregaTabelaCliente();
    }//GEN-LAST:event_ButtonListarClientesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelaDeletaConta;
    private javax.swing.JButton ButtonDeletaConta;
    private javax.swing.JButton ButtonListarClientes;
    private javax.swing.JPanel PanelContasClientesDeletaConta;
    private javax.swing.JPanel PanelSelecionaClienteDeletaConta;
    private javax.swing.JTable TableSelecionaClienteDeletaConta;
    private javax.swing.JTable TableSelecionaContaDeletaConta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
