/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Conta;

/**
 *
 * @author iuryi
 */
public class JF8Deposito extends javax.swing.JFrame {

    ArrayList<Cliente> ListaCliente;
    ArrayList<Conta> Contas;
    Conta contaDeposito;
//    double valorDeposito;
//    double saldoFinal;
//    double saldoAtual;
    int nContaDeposito;

    /**
     * Creates new form JFDeposito
     */
    public JF8Deposito(ArrayList<Cliente> ListaCliente, ArrayList<Conta> Contas) {
        initComponents();
        this.ListaCliente = ListaCliente;
        this.Contas = Contas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonConfirmaDeposito = new javax.swing.JButton();
        ButtonCancelaDeposito = new javax.swing.JButton();
        PanelDeposito = new javax.swing.JPanel();
        LabelNumContaDeposito = new javax.swing.JLabel();
        TextFieldInserirNumContaDeposito = new javax.swing.JTextField();
        LabelValorDeposito = new javax.swing.JLabel();
        TextFieldInserirValorDeposito = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ButtonConfirmaDeposito.setText("Confirmar");
        ButtonConfirmaDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmaDepositoActionPerformed(evt);
            }
        });

        ButtonCancelaDeposito.setText("Cancelar");
        ButtonCancelaDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelaDepositoActionPerformed(evt);
            }
        });

        PanelDeposito.setBorder(javax.swing.BorderFactory.createTitledBorder("Depósito"));

        LabelNumContaDeposito.setText("N° da Conta:");

        TextFieldInserirNumContaDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldInserirNumContaDepositoActionPerformed(evt);
            }
        });

        LabelValorDeposito.setText("Valor do Depósito:");

        TextFieldInserirValorDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldInserirValorDepositoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDepositoLayout = new javax.swing.GroupLayout(PanelDeposito);
        PanelDeposito.setLayout(PanelDepositoLayout);
        PanelDepositoLayout.setHorizontalGroup(
            PanelDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDepositoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDepositoLayout.createSequentialGroup()
                        .addComponent(LabelNumContaDeposito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldInserirNumContaDeposito))
                    .addGroup(PanelDepositoLayout.createSequentialGroup()
                        .addComponent(LabelValorDeposito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldInserirValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelDepositoLayout.setVerticalGroup(
            PanelDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDepositoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNumContaDeposito)
                    .addComponent(TextFieldInserirNumContaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelValorDeposito)
                    .addComponent(TextFieldInserirValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonConfirmaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(ButtonCancelaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonConfirmaDeposito)
                    .addComponent(ButtonCancelaDeposito))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldInserirNumContaDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldInserirNumContaDepositoActionPerformed
        // TODO add your handling code here:
        TextFieldInserirNumContaDeposito.getText();

    }//GEN-LAST:event_TextFieldInserirNumContaDepositoActionPerformed

    private void TextFieldInserirValorDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldInserirValorDepositoActionPerformed
        // TODO add your handling code here:
        TextFieldInserirValorDeposito.getText();

    }//GEN-LAST:event_TextFieldInserirValorDepositoActionPerformed

    private void ButtonConfirmaDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmaDepositoActionPerformed
        // TODO add your handling code here:
        //VERIFICAR COM O LUCAS SE PRECISA CONVERTER
        nContaDeposito = Integer.parseInt(TextFieldInserirNumContaDeposito.getText());
        double valorDeposito = Double.parseDouble(TextFieldInserirValorDeposito.getText());
        boolean achou = false;
        
        for (int i = 0; i < Contas.size(); i++) {
            if (nContaDeposito == Contas.get(i).getNumero()) {
                contaDeposito = Contas.get(i);
                achou = true;
                break;
            }
        }
        if (!achou) {
            JOptionPane.showMessageDialog(this, "Deposito falhou");
            TextFieldInserirNumContaDeposito.setText("");
            TextFieldInserirValorDeposito.setText("");
        }
        
//        saldoAtual = contaDeposito.getSaldo()+valorDeposito;
//        saldoFinal = saldoAtual + valorDeposito;
        contaDeposito.setSaldo(contaDeposito.getSaldo()+ valorDeposito);
        
        JOptionPane.showMessageDialog(this, "Saldo depositado com sucesso.");
        TextFieldInserirNumContaDeposito.setText("");
        TextFieldInserirValorDeposito.setText("");

    }//GEN-LAST:event_ButtonConfirmaDepositoActionPerformed

    private void ButtonCancelaDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelaDepositoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonCancelaDepositoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelaDeposito;
    private javax.swing.JButton ButtonConfirmaDeposito;
    private javax.swing.JLabel LabelNumContaDeposito;
    private javax.swing.JLabel LabelValorDeposito;
    private javax.swing.JPanel PanelDeposito;
    private javax.swing.JTextField TextFieldInserirNumContaDeposito;
    private javax.swing.JTextField TextFieldInserirValorDeposito;
    // End of variables declaration//GEN-END:variables
}
