/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Conta;

/**
 *
 * @author iuryi
 */
public class JF9_4RelatorioTodosClientes extends javax.swing.JFrame {

    ArrayList<Cliente> ListaCliente;
    ArrayList<Conta> Contas;

    /**
     * Creates new form JFRelatorioTodosClientes
     */
    public void CarregaTabelaCliente() {

        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"CPF", "Nome", "Sexo", "Data de Nascimento", "Endereço", "Conta", "Numero", "Saldo"}, 0);
        for (int i = 0; i < ListaCliente.size(); i++) {
            ArrayList<Conta> ListaConta = ListaCliente.get(i).getContas();
            for (int j = 0; j < ListaConta.size(); j++) {
                modelo.addRow(
                        new Object[]{
                            ListaCliente.get(i).getCPF(),
                            ListaCliente.get(i).getNome(),
                            ListaCliente.get(i).getSexo(),
                            ListaCliente.get(i).getDataNascimento(),
                            ListaCliente.get(i).getEndereco(),
                            ListaConta.get(j).getTipo(),
                            ListaConta.get(j).getNumero(),
                            ListaConta.get(j).getSaldo()});
                TableRelatorioTodosClientes.setModel(modelo);
            }
        }
    }

    public JF9_4RelatorioTodosClientes(ArrayList<Cliente> ListaCliente, ArrayList<Conta> Contas) {
        this.ListaCliente = ListaCliente;
        this.Contas = Contas;
        initComponents();
        this.CarregaTabelaCliente();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonOKRelatorioTodosClientes = new javax.swing.JButton();
        PanelRelatorioTodosClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableRelatorioTodosClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ButtonOKRelatorioTodosClientes.setText("OK");
        ButtonOKRelatorioTodosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOKRelatorioTodosClientesActionPerformed(evt);
            }
        });

        PanelRelatorioTodosClientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatório dos Clientes"));

        TableRelatorioTodosClientes.setAutoCreateRowSorter(true);
        TableRelatorioTodosClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Sexo", "Data de Nascimento", "Endereço", "Conta", "N° da Conta", "Saldo da Conta"
            }
        ));
        jScrollPane1.setViewportView(TableRelatorioTodosClientes);

        javax.swing.GroupLayout PanelRelatorioTodosClientesLayout = new javax.swing.GroupLayout(PanelRelatorioTodosClientes);
        PanelRelatorioTodosClientes.setLayout(PanelRelatorioTodosClientesLayout);
        PanelRelatorioTodosClientesLayout.setHorizontalGroup(
            PanelRelatorioTodosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRelatorioTodosClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelRelatorioTodosClientesLayout.setVerticalGroup(
            PanelRelatorioTodosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRelatorioTodosClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelRelatorioTodosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonOKRelatorioTodosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelRelatorioTodosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(ButtonOKRelatorioTodosClientes)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonOKRelatorioTodosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOKRelatorioTodosClientesActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonOKRelatorioTodosClientesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonOKRelatorioTodosClientes;
    private javax.swing.JPanel PanelRelatorioTodosClientes;
    private javax.swing.JTable TableRelatorioTodosClientes;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
