/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

//import Control.ControleBanco;
//import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Conta;

/**
 *
 * @author iuryi
 */
public class JF9_3RelatorioUmCliente extends javax.swing.JFrame {

    ArrayList<Cliente> ListaCliente;
    ArrayList<Conta> Contas;
   // ControleBanco controleBanco;
    Cliente relatorioCliente;

    /**
     * Creates new form JFRelatorioCliente
     */
    public void CarregaTabelaConta() {
        ArrayList<Conta> relatorioConta = relatorioCliente.getContas();
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Conta", "Numero", "Saldo"}, 0);
        for (int i = 0; i < relatorioConta.size(); i++) {
            modelo.addRow(new Object[]{relatorioConta.get(i).getTipo(),
                relatorioConta.get(i).getNumero(),
                relatorioConta.get(i).getSaldo()});
            TableRelatorioContasUmCliente.setModel(modelo);
        }
    }

    public JF9_3RelatorioUmCliente(ArrayList<Cliente> ListaCliente, ArrayList<Conta> Contas) {
        this.ListaCliente = ListaCliente;
        this.Contas = Contas;
        initComponents();
        // this.CarregaTabelaConta();
      //  controleBanco = new ControleBanco();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonCancelarRelatorioUmCliente = new javax.swing.JButton();
        PanelRelatorioUmCliente1 = new javax.swing.JPanel();
        LabelNomeCliente = new javax.swing.JLabel();
        TextFieldNomeCliente = new javax.swing.JTextField();
        LabelDataNascimento = new javax.swing.JLabel();
        TextFieldDataNascimento = new javax.swing.JTextField();
        LabelSexoCliente = new javax.swing.JLabel();
        TextFieldSexoCliente = new javax.swing.JTextField();
        LabelEndereco = new javax.swing.JLabel();
        TextFieldEnderecoCliente = new javax.swing.JTextField();
        PanelRelatorioContasUmCliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableRelatorioContasUmCliente = new javax.swing.JTable();
        LabelCpfCliente = new javax.swing.JLabel();
        TextFieldCpfCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TextFieldInserirCpfBuscaRelatorioUmCliente = new javax.swing.JTextField();
        ButtonBuscaCpfRelatorioUmCliente = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ButtonCancelarRelatorioUmCliente.setText("Cancelar");
        ButtonCancelarRelatorioUmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarRelatorioUmClienteActionPerformed(evt);
            }
        });

        PanelRelatorioUmCliente1.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatório do Cliente"));

        LabelNomeCliente.setText("Nome:");

        TextFieldNomeCliente.setName(""); // NOI18N
        TextFieldNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNomeClienteActionPerformed(evt);
            }
        });

        LabelDataNascimento.setText("Data Nascimento:");

        TextFieldDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDataNascimentoActionPerformed(evt);
            }
        });

        LabelSexoCliente.setText("Sexo:");

        TextFieldSexoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldSexoClienteActionPerformed(evt);
            }
        });

        LabelEndereco.setText("Endereço:");

        TextFieldEnderecoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldEnderecoClienteActionPerformed(evt);
            }
        });

        PanelRelatorioContasUmCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatório de Contas do Clientes"));

        TableRelatorioContasUmCliente.setAutoCreateRowSorter(true);
        TableRelatorioContasUmCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Conta", "N° da Conta", "Saldo da Conta"
            }
        ));
        jScrollPane1.setViewportView(TableRelatorioContasUmCliente);

        javax.swing.GroupLayout PanelRelatorioContasUmClienteLayout = new javax.swing.GroupLayout(PanelRelatorioContasUmCliente);
        PanelRelatorioContasUmCliente.setLayout(PanelRelatorioContasUmClienteLayout);
        PanelRelatorioContasUmClienteLayout.setHorizontalGroup(
            PanelRelatorioContasUmClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        PanelRelatorioContasUmClienteLayout.setVerticalGroup(
            PanelRelatorioContasUmClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRelatorioContasUmClienteLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        LabelCpfCliente.setText("CPF:");

        TextFieldCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCpfClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRelatorioUmCliente1Layout = new javax.swing.GroupLayout(PanelRelatorioUmCliente1);
        PanelRelatorioUmCliente1.setLayout(PanelRelatorioUmCliente1Layout);
        PanelRelatorioUmCliente1Layout.setHorizontalGroup(
            PanelRelatorioUmCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRelatorioContasUmCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelRelatorioUmCliente1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRelatorioUmCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRelatorioUmCliente1Layout.createSequentialGroup()
                        .addComponent(LabelNomeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelCpfCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelDataNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelSexoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldSexoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelRelatorioUmCliente1Layout.createSequentialGroup()
                        .addComponent(LabelEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldEnderecoCliente)
                        .addGap(60, 60, 60))))
        );
        PanelRelatorioUmCliente1Layout.setVerticalGroup(
            PanelRelatorioUmCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRelatorioUmCliente1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRelatorioUmCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNomeCliente)
                    .addComponent(TextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCpfCliente)
                    .addComponent(TextFieldCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDataNascimento)
                    .addComponent(TextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSexoCliente)
                    .addComponent(TextFieldSexoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRelatorioUmCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEndereco)
                    .addComponent(TextFieldEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PanelRelatorioContasUmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel1.setText("CPF:");

        TextFieldInserirCpfBuscaRelatorioUmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldInserirCpfBuscaRelatorioUmClienteActionPerformed(evt);
            }
        });

        ButtonBuscaCpfRelatorioUmCliente.setText("Buscar");
        ButtonBuscaCpfRelatorioUmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscaCpfRelatorioUmClienteActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldInserirCpfBuscaRelatorioUmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonBuscaCpfRelatorioUmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonCancelarRelatorioUmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(PanelRelatorioUmCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextFieldInserirCpfBuscaRelatorioUmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBuscaCpfRelatorioUmCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelRelatorioUmCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar)
                    .addComponent(ButtonCancelarRelatorioUmCliente))
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldInserirCpfBuscaRelatorioUmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldInserirCpfBuscaRelatorioUmClienteActionPerformed
        // TODO add your handling code here:
        TextFieldInserirCpfBuscaRelatorioUmCliente.getText();
    }//GEN-LAST:event_TextFieldInserirCpfBuscaRelatorioUmClienteActionPerformed

    private void ButtonBuscaCpfRelatorioUmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscaCpfRelatorioUmClienteActionPerformed
        // TODO add your handling code here:
        boolean achou = false;
        for (int i = 0; i < ListaCliente.size(); i++) {
            if (TextFieldInserirCpfBuscaRelatorioUmCliente.getText().equals(ListaCliente.get(i).getCPF())) {
                relatorioCliente = ListaCliente.get(i);
                achou = true;
                break;
            }
        }
        if (!achou) {
            JOptionPane.showMessageDialog(this, "CPF não encontrado");
            TextFieldInserirCpfBuscaRelatorioUmCliente.setText("");
        }

        TextFieldNomeCliente.setText(relatorioCliente.getNome());
        TextFieldCpfCliente.setText(relatorioCliente.getCPF());
        TextFieldEnderecoCliente.setText(relatorioCliente.getEndereco());
        TextFieldDataNascimento.setText(relatorioCliente.getDataNascimento());
        TextFieldSexoCliente.setText(relatorioCliente.getSexo());
        this.CarregaTabelaConta();

    }//GEN-LAST:event_ButtonBuscaCpfRelatorioUmClienteActionPerformed

    private void ButtonCancelarRelatorioUmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarRelatorioUmClienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonCancelarRelatorioUmClienteActionPerformed

    private void TextFieldDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDataNascimentoActionPerformed

    private void TextFieldNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeClienteActionPerformed

    private void TextFieldCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCpfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCpfClienteActionPerformed

    private void TextFieldSexoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldSexoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldSexoClienteActionPerformed

    private void TextFieldEnderecoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldEnderecoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldEnderecoClienteActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        TextFieldInserirCpfBuscaRelatorioUmCliente.setText("");
        TextFieldNomeCliente.setText("");
        TextFieldCpfCliente.setText("");
        TextFieldEnderecoCliente.setText("");
        TextFieldDataNascimento.setText("");
        TextFieldSexoCliente.setText("");
        ((DefaultTableModel) TableRelatorioContasUmCliente.getModel()).setRowCount(0);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscaCpfRelatorioUmCliente;
    private javax.swing.JButton ButtonCancelarRelatorioUmCliente;
    private javax.swing.JLabel LabelCpfCliente;
    private javax.swing.JLabel LabelDataNascimento;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelNomeCliente;
    private javax.swing.JLabel LabelSexoCliente;
    private javax.swing.JPanel PanelRelatorioContasUmCliente;
    private javax.swing.JPanel PanelRelatorioUmCliente1;
    private javax.swing.JTable TableRelatorioContasUmCliente;
    private javax.swing.JTextField TextFieldCpfCliente;
    private javax.swing.JTextField TextFieldDataNascimento;
    private javax.swing.JTextField TextFieldEnderecoCliente;
    private javax.swing.JTextField TextFieldInserirCpfBuscaRelatorioUmCliente;
    private javax.swing.JTextField TextFieldNomeCliente;
    private javax.swing.JTextField TextFieldSexoCliente;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
