/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 *
 * @author iuryi
 */
public class JFAtualizaCliente extends javax.swing.JFrame {
ArrayList<Cliente> ListaCliente;
    /**
     * Creates new form JFAtualizaCliente
     */

        private void groupButton( ) {
       
ButtonGroup bg1 = new ButtonGroup( );

bg1.add(RadioButtonSexoHomem);
bg1.add(RadioButtonSexoMulher);
}

public void CarregaTabelaCliente(ArrayList<Cliente> minhaLista){
    DefaultTableModel modelo = new DefaultTableModel(new Object[]{"CPF","Nome","Sexo","Data de Nascimento","Endereço"},0);
    for(int i=0;i<minhaLista.size();i++){
        modelo.addRow(new Object[]{minhaLista.get(i).getCPF(),minhaLista.get(i).getNome(),minhaLista.get(i).getSexo(),minhaLista.get(i).getDataNascimento(),minhaLista.get(i).getEndereco()});
    }    
    TableAtualizaCliente.setModel(modelo);
    }

public JFAtualizaCliente() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        LabelCpfAtualizaCliente = new javax.swing.JLabel();
        ButtonBuscaCpfAtualizaCliente = new javax.swing.JButton();
        TextFildInserirCpfBuscaAtualizaCliente = new javax.swing.JTextField();
        PanelAtualizaCliente = new javax.swing.JPanel();
        LabelNomeAtualizaCliente = new javax.swing.JLabel();
        TextFildInserirNomeAtualizaCliente = new javax.swing.JTextField();
        LabelDataNascimentoAtualizaCliente = new javax.swing.JLabel();
        LabelSexoAtualizaCliente = new javax.swing.JLabel();
        LabelEnderecoAtualizaCliente = new javax.swing.JLabel();
        TextFildInseirEnderecoAtualizaCliente = new javax.swing.JTextField();
        TextFildInserirDataNascimentoAtualizaCliente = new javax.swing.JTextField();
        RadioButtonSexoHomem = new javax.swing.JRadioButton();
        RadioButtonSexoMulher = new javax.swing.JRadioButton();
        ButtonAtualizaCliente = new javax.swing.JButton();
        ButtonCancelarAtualizaCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAtualizaCliente = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelCpfAtualizaCliente.setText("CPF:");

        ButtonBuscaCpfAtualizaCliente.setText("Buscar");
        ButtonBuscaCpfAtualizaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscaCpfAtualizaClienteActionPerformed(evt);
            }
        });

        TextFildInserirCpfBuscaAtualizaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFildInserirCpfBuscaAtualizaClienteActionPerformed(evt);
            }
        });

        PanelAtualizaCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Atualizar Dados do Cliente"));

        LabelNomeAtualizaCliente.setText("Nome:");

        TextFildInserirNomeAtualizaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFildInserirNomeAtualizaClienteActionPerformed(evt);
            }
        });

        LabelDataNascimentoAtualizaCliente.setText("Data de Nascimento:");

        LabelSexoAtualizaCliente.setText("Sexo:");

        LabelEnderecoAtualizaCliente.setText("Endereço:");

        TextFildInseirEnderecoAtualizaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFildInseirEnderecoAtualizaClienteActionPerformed(evt);
            }
        });

        TextFildInserirDataNascimentoAtualizaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFildInserirDataNascimentoAtualizaClienteActionPerformed(evt);
            }
        });

        RadioButtonSexoHomem.setText("Homem");
        RadioButtonSexoHomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSexoHomemActionPerformed(evt);
            }
        });

        RadioButtonSexoMulher.setText("Mulher");
        RadioButtonSexoMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSexoMulherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAtualizaClienteLayout = new javax.swing.GroupLayout(PanelAtualizaCliente);
        PanelAtualizaCliente.setLayout(PanelAtualizaClienteLayout);
        PanelAtualizaClienteLayout.setHorizontalGroup(
            PanelAtualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAtualizaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAtualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAtualizaClienteLayout.createSequentialGroup()
                        .addComponent(LabelEnderecoAtualizaCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFildInseirEnderecoAtualizaCliente))
                    .addGroup(PanelAtualizaClienteLayout.createSequentialGroup()
                        .addGroup(PanelAtualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAtualizaClienteLayout.createSequentialGroup()
                                .addComponent(LabelDataNascimentoAtualizaCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFildInserirDataNascimentoAtualizaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAtualizaClienteLayout.createSequentialGroup()
                                .addComponent(LabelNomeAtualizaCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFildInserirNomeAtualizaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAtualizaClienteLayout.createSequentialGroup()
                                .addComponent(LabelSexoAtualizaCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonSexoHomem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonSexoMulher)))
                        .addGap(0, 241, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelAtualizaClienteLayout.setVerticalGroup(
            PanelAtualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAtualizaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAtualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNomeAtualizaCliente)
                    .addComponent(TextFildInserirNomeAtualizaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAtualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDataNascimentoAtualizaCliente)
                    .addComponent(TextFildInserirDataNascimentoAtualizaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAtualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSexoAtualizaCliente)
                    .addComponent(RadioButtonSexoHomem)
                    .addComponent(RadioButtonSexoMulher))
                .addGap(6, 6, 6)
                .addGroup(PanelAtualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEnderecoAtualizaCliente)
                    .addComponent(TextFildInseirEnderecoAtualizaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        ButtonAtualizaCliente.setText("Atualizar");
        ButtonAtualizaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAtualizaClienteActionPerformed(evt);
            }
        });

        ButtonCancelarAtualizaCliente.setText("Cancelar");
        ButtonCancelarAtualizaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarAtualizaClienteActionPerformed(evt);
            }
        });

        TableAtualizaCliente.setAutoCreateRowSorter(true);
        TableAtualizaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Sexo", "Data de Nascimento", "Endereço"
            }
        ));
        TableAtualizaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableAtualizaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableAtualizaCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelAtualizaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelCpfAtualizaCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFildInserirCpfBuscaAtualizaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonBuscaCpfAtualizaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonAtualizaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonCancelarAtualizaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCpfAtualizaCliente)
                    .addComponent(TextFildInserirCpfBuscaAtualizaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBuscaCpfAtualizaCliente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelAtualizaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAtualizaCliente)
                    .addComponent(ButtonCancelarAtualizaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFildInserirCpfBuscaAtualizaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFildInserirCpfBuscaAtualizaClienteActionPerformed
        // TODO add your handling code here:
        TextFildInserirCpfBuscaAtualizaCliente.getText();
    }//GEN-LAST:event_TextFildInserirCpfBuscaAtualizaClienteActionPerformed

    private void ButtonBuscaCpfAtualizaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscaCpfAtualizaClienteActionPerformed
        // TODO add your handling code here:
        ArrayList<Cliente> minhaLista = new ArrayList();
        
        for(int i=0;i<ListaCliente.size();i++){
            if(TextFildInserirCpfBuscaAtualizaCliente.getText().equals(ListaCliente.get(i).getCPF())){
                minhaLista.add(ListaCliente.get(i));
                CarregaTabelaCliente(minhaLista);
                break;
            }
            else{
            JOptionPane.showMessageDialog(this,"CPF não encontrado");
            TextFildInserirCpfBuscaAtualizaCliente.setText("");}
        }
    }//GEN-LAST:event_ButtonBuscaCpfAtualizaClienteActionPerformed

    private void TextFildInserirNomeAtualizaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFildInserirNomeAtualizaClienteActionPerformed
        // TODO add your handling code here:
        int index = TableAtualizaCliente.getSelectedRow();
        TextFildInserirNomeAtualizaCliente.setText(ListaCliente.get(index).getNome());
    
    }//GEN-LAST:event_TextFildInserirNomeAtualizaClienteActionPerformed

    private void TextFildInserirDataNascimentoAtualizaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFildInserirDataNascimentoAtualizaClienteActionPerformed
        // TODO add your handling code here:
        int index = TableAtualizaCliente.getSelectedRow();
       TextFildInserirDataNascimentoAtualizaCliente.setText(ListaCliente.get(index).getDataNascimento());
    }//GEN-LAST:event_TextFildInserirDataNascimentoAtualizaClienteActionPerformed

    private void TextFildInseirEnderecoAtualizaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFildInseirEnderecoAtualizaClienteActionPerformed
        // TODO add your handling code here:
        int index = TableAtualizaCliente.getSelectedRow();
        TextFildInseirEnderecoAtualizaCliente.setText(ListaCliente.get(index).getEndereco());
    }//GEN-LAST:event_TextFildInseirEnderecoAtualizaClienteActionPerformed

    private void ButtonAtualizaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAtualizaClienteActionPerformed
        // TODO add your handling code here:
      //  int index = TableAtualizaCliente.getSelectedRow();
      Cliente cliAtualizacao = new Cliente();
      int index = -1;
         for(int i=0;i<ListaCliente.size();i++){
            if(TextFildInserirCpfBuscaAtualizaCliente.getText().equals(ListaCliente.get(i).getCPF())){
                cliAtualizacao = ListaCliente.get(i);
                index = i;
                break;
            }
         }
         
        cliAtualizacao.setNome(TextFildInserirNomeAtualizaCliente.getText());
        cliAtualizacao.setDataNascimento(TextFildInserirDataNascimentoAtualizaCliente.getText());
        cliAtualizacao.setEndereco(TextFildInseirEnderecoAtualizaCliente.getText());
        cliAtualizacao.setSexo(RadioButtonSexoMulher.isSelected()? "Feminino" : "Masculino" );
        
        ListaCliente.set(index, cliAtualizacao);
        
        ArrayList<Cliente> tabelaLista = new ArrayList();
        tabelaLista.add(ListaCliente.get(index));
        CarregaTabelaCliente(tabelaLista);
      TextFildInserirNomeAtualizaCliente.setText("");
      TextFildInserirDataNascimentoAtualizaCliente.setText("");
      TextFildInseirEnderecoAtualizaCliente.setText("");
      TextFildInserirNomeAtualizaCliente.setText("");
      TextFildInserirCpfBuscaAtualizaCliente.setText("");
        JOptionPane.showMessageDialog(rootPane, "Dados atualizados com sucesso.");
    }//GEN-LAST:event_ButtonAtualizaClienteActionPerformed

    private void ButtonCancelarAtualizaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarAtualizaClienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonCancelarAtualizaClienteActionPerformed

    private void TableAtualizaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableAtualizaClienteMouseClicked
        // TODO add your handling code here:
        TableAtualizaCliente.getSelectedRow();
    }//GEN-LAST:event_TableAtualizaClienteMouseClicked

    private void RadioButtonSexoHomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSexoHomemActionPerformed
        // TODO add your handling code here:
        RadioButtonSexoHomem.isSelected();
    }//GEN-LAST:event_RadioButtonSexoHomemActionPerformed

    private void RadioButtonSexoMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSexoMulherActionPerformed
        // TODO add your handling code here:
        RadioButtonSexoMulher.isSelected();
    }//GEN-LAST:event_RadioButtonSexoMulherActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAtualizaCliente;
    private javax.swing.JButton ButtonBuscaCpfAtualizaCliente;
    private javax.swing.JButton ButtonCancelarAtualizaCliente;
    private javax.swing.JLabel LabelCpfAtualizaCliente;
    private javax.swing.JLabel LabelDataNascimentoAtualizaCliente;
    private javax.swing.JLabel LabelEnderecoAtualizaCliente;
    private javax.swing.JLabel LabelNomeAtualizaCliente;
    private javax.swing.JLabel LabelSexoAtualizaCliente;
    private javax.swing.JPanel PanelAtualizaCliente;
    private javax.swing.JRadioButton RadioButtonSexoHomem;
    private javax.swing.JRadioButton RadioButtonSexoMulher;
    private javax.swing.JTable TableAtualizaCliente;
    private javax.swing.JTextField TextFildInseirEnderecoAtualizaCliente;
    private javax.swing.JTextField TextFildInserirCpfBuscaAtualizaCliente;
    private javax.swing.JTextField TextFildInserirDataNascimentoAtualizaCliente;
    private javax.swing.JTextField TextFildInserirNomeAtualizaCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
