/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 *
 * @author iuryi
 */
public class JFDeletaCliente extends javax.swing.JFrame {
ArrayList<Cliente> ListaCliente;
    /**
     * Creates new form JFDeletaCliente
     */
    
    public void CarregaTabelaCliente(){
    DefaultTableModel modelo = new DefaultTableModel(new Object[]{"CPF","Nome","Sexo","Data de Nascimento","Endereço"},0);
    for(int i=0;i<ListaCliente.size();i++){
        modelo.addRow(new Object[]{ListaCliente.get(i).getCPF(),ListaCliente.get(i).getNome(),ListaCliente.get(i).getSexo(),ListaCliente.get(i).getDataNascimento(),ListaCliente.get(i).getEndereco()});
    }    
    TableDeletaCliente.setModel(modelo);
    }
    
    
    public JFDeletaCliente() {
        initComponents();
        ListaCliente = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelCpf = new javax.swing.JLabel();
        TextFildInserirCpfBuscaDeletaCliente = new javax.swing.JTextField();
        ButtonBuscarCpfDeletaCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDeletaCliente = new javax.swing.JTable();
        ButtonDeletaCliente = new javax.swing.JButton();
        ButtonCancelarDeletaCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelCpf.setText("CPF:");

        TextFildInserirCpfBuscaDeletaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFildInserirCpfBuscaDeletaClienteActionPerformed(evt);
            }
        });

        ButtonBuscarCpfDeletaCliente.setText("Buscar");
        ButtonBuscarCpfDeletaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarCpfDeletaClienteActionPerformed(evt);
            }
        });

        TableDeletaCliente.setAutoCreateRowSorter(true);
        TableDeletaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Sexo", "Data de Nascimento", "Endereço"
            }
        ));
        TableDeletaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDeletaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableDeletaCliente);

        ButtonDeletaCliente.setText("Deletar");
        ButtonDeletaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeletaClienteActionPerformed(evt);
            }
        });

        ButtonCancelarDeletaCliente.setText("Cancelar");
        ButtonCancelarDeletaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarDeletaClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFildInserirCpfBuscaDeletaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonBuscarCpfDeletaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonDeletaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonCancelarDeletaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFildInserirCpfBuscaDeletaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCpf)
                    .addComponent(ButtonBuscarCpfDeletaCliente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDeletaCliente)
                    .addComponent(ButtonCancelarDeletaCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFildInserirCpfBuscaDeletaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFildInserirCpfBuscaDeletaClienteActionPerformed
        // TODO add your handling code here:
        TextFildInserirCpfBuscaDeletaCliente.getText();
    }//GEN-LAST:event_TextFildInserirCpfBuscaDeletaClienteActionPerformed

    private void ButtonBuscarCpfDeletaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarCpfDeletaClienteActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<ListaCliente.size();i++){
        if(TextFildInserirCpfBuscaDeletaCliente.getText().equals(ListaCliente.get(i).getCPF())){
        CarregaTabelaCliente();    
    }   
        else{
            JOptionPane.showMessageDialog(this,"CPF não encontrado");
            TextFildInserirCpfBuscaDeletaCliente.setText("");
            
        }
        }
        
    }//GEN-LAST:event_ButtonBuscarCpfDeletaClienteActionPerformed

    private void TableDeletaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDeletaClienteMouseClicked
        // TODO add your handling code here:
        TableDeletaCliente.getSelectedRow();
    }//GEN-LAST:event_TableDeletaClienteMouseClicked

    private void ButtonDeletaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeletaClienteActionPerformed
        int index = TableDeletaCliente.getSelectedRow();
        if(index>=0 && index<ListaCliente.size()){
        TableDeletaCliente.remove(index);
        CarregaTabelaCliente();
        }
        
    }//GEN-LAST:event_ButtonDeletaClienteActionPerformed

    private void ButtonCancelarDeletaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarDeletaClienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonCancelarDeletaClienteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscarCpfDeletaCliente;
    private javax.swing.JButton ButtonCancelarDeletaCliente;
    private javax.swing.JButton ButtonDeletaCliente;
    private javax.swing.JLabel LabelCpf;
    private javax.swing.JTable TableDeletaCliente;
    private javax.swing.JTextField TextFildInserirCpfBuscaDeletaCliente;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
