/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Conta;
import model.ContaCorrente;
import model.ContaPoupanca;

/**
 *
 * @author iuryi
 */
public class JFNovoCliente extends javax.swing.JFrame {
    ArrayList<Cliente> ListaCliente;
    ArrayList<Conta> Contas;
    double saldo;
    /**
     * Creates new form JFNovoCliente
     */
    
        private void groupButton( ) {

ButtonGroup bg1 = new ButtonGroup( );

bg1.add(RadioButtonSelecionaContaCorrente);
bg1.add(RadioButtonSelecionaContaPoupanca);

        
ButtonGroup bg2 = new ButtonGroup( );

bg2.add(RadioButtonSexoHomem);
bg2.add(RadioButtonSexoMulher);
}
    
    public JFNovoCliente() {
        initComponents();
        ListaCliente = new ArrayList();
        Contas  = new ArrayList();
        groupButton();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonSalvarNovoCliente = new javax.swing.JButton();
        ButtonCancelarNovoCliente = new javax.swing.JButton();
        PanelCadastraCliente = new javax.swing.JPanel();
        LabelNomeCadastraCliente = new javax.swing.JLabel();
        TextFildInserirNomeNovoCliente = new javax.swing.JTextField();
        LabelCadastraCliente = new javax.swing.JLabel();
        TextFildInserirCpfNovoCliente = new javax.swing.JTextField();
        LabelDataNascimentoCadastraCliente = new javax.swing.JLabel();
        TextFildInserirDataNascimentoNovoCliente = new javax.swing.JFormattedTextField();
        LabelSexoCadastraCliente = new javax.swing.JLabel();
        LabelEnderecoCadastraCliente = new javax.swing.JLabel();
        TextFildInserirEnderecoNovoCliente = new javax.swing.JTextField();
        PanelCadastraConta = new javax.swing.JPanel();
        LabelTipoDeContaCadastraCliente = new javax.swing.JLabel();
        LabelSaldoInicialCadastraCliente = new javax.swing.JLabel();
        TextFildInserirSaldoInicialContaNovoCliente = new javax.swing.JTextField();
        RadioButtonSelecionaContaCorrente = new javax.swing.JRadioButton();
        RadioButtonSelecionaContaPoupanca = new javax.swing.JRadioButton();
        RadioButtonSexoHomem = new javax.swing.JRadioButton();
        RadioButtonSexoMulher = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonSalvarNovoCliente.setText("Salvar");
        ButtonSalvarNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarNovoClienteActionPerformed(evt);
            }
        });

        ButtonCancelarNovoCliente.setText("Cancelar");
        ButtonCancelarNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarNovoClienteActionPerformed(evt);
            }
        });

        PanelCadastraCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadrastar Cliente"));

        LabelNomeCadastraCliente.setText("Nome:");

        TextFildInserirNomeNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFildInserirNomeNovoClienteActionPerformed(evt);
            }
        });

        LabelCadastraCliente.setText("CPF:");

        TextFildInserirCpfNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFildInserirCpfNovoClienteActionPerformed(evt);
            }
        });

        LabelDataNascimentoCadastraCliente.setText("Data de Nascimento:");

        TextFildInserirDataNascimentoNovoCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        TextFildInserirDataNascimentoNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFildInserirDataNascimentoNovoClienteActionPerformed(evt);
            }
        });

        LabelSexoCadastraCliente.setText("Sexo:");

        LabelEnderecoCadastraCliente.setText("Endereço:");

        TextFildInserirEnderecoNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFildInserirEnderecoNovoClienteActionPerformed(evt);
            }
        });

        PanelCadastraConta.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta"));

        LabelTipoDeContaCadastraCliente.setText("Tipo de Conta:");

        LabelSaldoInicialCadastraCliente.setText("Saldo Inicial:");

        TextFildInserirSaldoInicialContaNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFildInserirSaldoInicialContaNovoClienteActionPerformed(evt);
            }
        });

        RadioButtonSelecionaContaCorrente.setText("Conta Corrente");
        RadioButtonSelecionaContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSelecionaContaCorrenteActionPerformed(evt);
            }
        });

        RadioButtonSelecionaContaPoupanca.setText("Conta Poupança");
        RadioButtonSelecionaContaPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSelecionaContaPoupancaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCadastraContaLayout = new javax.swing.GroupLayout(PanelCadastraConta);
        PanelCadastraConta.setLayout(PanelCadastraContaLayout);
        PanelCadastraContaLayout.setHorizontalGroup(
            PanelCadastraContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastraContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCadastraContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastraContaLayout.createSequentialGroup()
                        .addComponent(LabelTipoDeContaCadastraCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioButtonSelecionaContaCorrente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioButtonSelecionaContaPoupanca))
                    .addGroup(PanelCadastraContaLayout.createSequentialGroup()
                        .addComponent(LabelSaldoInicialCadastraCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFildInserirSaldoInicialContaNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 303, Short.MAX_VALUE))
        );
        PanelCadastraContaLayout.setVerticalGroup(
            PanelCadastraContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastraContaLayout.createSequentialGroup()
                .addGroup(PanelCadastraContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTipoDeContaCadastraCliente)
                    .addComponent(RadioButtonSelecionaContaCorrente)
                    .addComponent(RadioButtonSelecionaContaPoupanca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadastraContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSaldoInicialCadastraCliente)
                    .addComponent(TextFildInserirSaldoInicialContaNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        RadioButtonSexoHomem.setText("Homem");
        RadioButtonSexoHomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSexoHomemActionPerformed(evt);
            }
        });

        RadioButtonSexoMulher.setText("Mulher");
        RadioButtonSexoMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSexoMulherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCadastraClienteLayout = new javax.swing.GroupLayout(PanelCadastraCliente);
        PanelCadastraCliente.setLayout(PanelCadastraClienteLayout);
        PanelCadastraClienteLayout.setHorizontalGroup(
            PanelCadastraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastraClienteLayout.createSequentialGroup()
                .addGroup(PanelCadastraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastraClienteLayout.createSequentialGroup()
                        .addComponent(LabelNomeCadastraCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFildInserirNomeNovoCliente))
                    .addComponent(PanelCadastraConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelCadastraClienteLayout.createSequentialGroup()
                        .addComponent(LabelEnderecoCadastraCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFildInserirEnderecoNovoCliente))
                    .addGroup(PanelCadastraClienteLayout.createSequentialGroup()
                        .addGroup(PanelCadastraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCadastraCliente)
                            .addComponent(LabelSexoCadastraCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelCadastraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCadastraClienteLayout.createSequentialGroup()
                                .addComponent(TextFildInserirCpfNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelDataNascimentoCadastraCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFildInserirDataNascimentoNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelCadastraClienteLayout.createSequentialGroup()
                                .addComponent(RadioButtonSexoHomem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonSexoMulher)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelCadastraClienteLayout.setVerticalGroup(
            PanelCadastraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastraClienteLayout.createSequentialGroup()
                .addGroup(PanelCadastraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNomeCadastraCliente)
                    .addComponent(TextFildInserirNomeNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadastraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCadastraCliente)
                    .addComponent(TextFildInserirCpfNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDataNascimentoCadastraCliente)
                    .addComponent(TextFildInserirDataNascimentoNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadastraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSexoCadastraCliente)
                    .addComponent(RadioButtonSexoHomem)
                    .addComponent(RadioButtonSexoMulher))
                .addGap(7, 7, 7)
                .addGroup(PanelCadastraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEnderecoCadastraCliente)
                    .addComponent(TextFildInserirEnderecoNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(PanelCadastraConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCadastraCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonSalvarNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonCancelarNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelCadastraCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSalvarNovoCliente)
                    .addComponent(ButtonCancelarNovoCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFildInserirNomeNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFildInserirNomeNovoClienteActionPerformed
        // TODO add your handling code here:
        TextFildInserirNomeNovoCliente.getText();
    }//GEN-LAST:event_TextFildInserirNomeNovoClienteActionPerformed

    private void TextFildInserirCpfNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFildInserirCpfNovoClienteActionPerformed
        // TODO add your handling code here:
        TextFildInserirCpfNovoCliente.getText();
    }//GEN-LAST:event_TextFildInserirCpfNovoClienteActionPerformed

    private void TextFildInserirDataNascimentoNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFildInserirDataNascimentoNovoClienteActionPerformed
        // TODO add your handling code here:
        TextFildInserirDataNascimentoNovoCliente.getText();
    }//GEN-LAST:event_TextFildInserirDataNascimentoNovoClienteActionPerformed

    private void TextFildInserirEnderecoNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFildInserirEnderecoNovoClienteActionPerformed
        // TODO add your handling code here:
        TextFildInserirEnderecoNovoCliente.getText();
    }//GEN-LAST:event_TextFildInserirEnderecoNovoClienteActionPerformed

    private void RadioButtonSelecionaContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSelecionaContaCorrenteActionPerformed
        // TODO add your handling code here:
        RadioButtonSelecionaContaCorrente.isSelected();
        // AINDA NÃO DESCOBRI COMO IMPLEMENTAR ESSA DESGRAÇA AAAAAAAAAAAAAAAAAAAAA!
    }//GEN-LAST:event_RadioButtonSelecionaContaCorrenteActionPerformed

    private void RadioButtonSelecionaContaPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSelecionaContaPoupancaActionPerformed
        // TODO add your handling code here:
        RadioButtonSelecionaContaPoupanca.isSelected();
        // AINDA NÃO DESCOBRI COMO IMPLEMENTAR ESSA DESGRAÇA AAAAAAAAAAAAAAAAAAAAA!
    }//GEN-LAST:event_RadioButtonSelecionaContaPoupancaActionPerformed

    private void TextFildInserirSaldoInicialContaNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFildInserirSaldoInicialContaNovoClienteActionPerformed
        // TODO add your handling code here:
        saldo = Double.parseDouble(TextFildInserirSaldoInicialContaNovoCliente.getText());
    }//GEN-LAST:event_TextFildInserirSaldoInicialContaNovoClienteActionPerformed

    private void ButtonSalvarNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarNovoClienteActionPerformed
        // TODO add your handling code here:
        Cliente c = new Cliente();
        c.setCPF(TextFildInserirCpfNovoCliente.getText());        
        c.setNome(TextFildInserirNomeNovoCliente.getText());
        c.setDataNascimento(TextFildInserirDataNascimentoNovoCliente.getText());
        c.setSexo(RadioButtonSexoMulher.isSelected()? "Feminino" : "Masculino" );  
        c.setEndereco(TextFildInserirEnderecoNovoCliente.getText());
        Conta cb = RadioButtonSelecionaContaCorrente.isSelected() 
                ? new ContaCorrente(c,saldo) 
                : new ContaPoupanca(c,saldo);
        c.adicionarConta(cb); 
        ListaCliente.add(c);
        JOptionPane.showMessageDialog(rootPane, "Dados cadastrados com sucesso.");
       TextFildInserirCpfNovoCliente.setText("");        
       TextFildInserirNomeNovoCliente.setText("");
       TextFildInserirDataNascimentoNovoCliente.setText("");
       RadioButtonSexoMulher.isSelected();
       RadioButtonSexoHomem.isSelected(); 
       TextFildInserirEnderecoNovoCliente.setText("");
       RadioButtonSelecionaContaCorrente.isSelected();
       RadioButtonSelecionaContaPoupanca.isSelected();
       TextFildInserirSaldoInicialContaNovoCliente.setText("");
    }//GEN-LAST:event_ButtonSalvarNovoClienteActionPerformed
 
    private void ButtonCancelarNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarNovoClienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonCancelarNovoClienteActionPerformed

    private void RadioButtonSexoHomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSexoHomemActionPerformed
        // TODO add your handling code here:
        RadioButtonSexoHomem.isSelected();
    }//GEN-LAST:event_RadioButtonSexoHomemActionPerformed

    private void RadioButtonSexoMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSexoMulherActionPerformed
        // TODO add your handling code here:
        RadioButtonSexoMulher.isSelected();
    }//GEN-LAST:event_RadioButtonSexoMulherActionPerformed

    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelarNovoCliente;
    private javax.swing.JButton ButtonSalvarNovoCliente;
    private javax.swing.JLabel LabelCadastraCliente;
    private javax.swing.JLabel LabelDataNascimentoCadastraCliente;
    private javax.swing.JLabel LabelEnderecoCadastraCliente;
    private javax.swing.JLabel LabelNomeCadastraCliente;
    private javax.swing.JLabel LabelSaldoInicialCadastraCliente;
    private javax.swing.JLabel LabelSexoCadastraCliente;
    private javax.swing.JLabel LabelTipoDeContaCadastraCliente;
    private javax.swing.JPanel PanelCadastraCliente;
    private javax.swing.JPanel PanelCadastraConta;
    private javax.swing.JRadioButton RadioButtonSelecionaContaCorrente;
    private javax.swing.JRadioButton RadioButtonSelecionaContaPoupanca;
    private javax.swing.JRadioButton RadioButtonSexoHomem;
    private javax.swing.JRadioButton RadioButtonSexoMulher;
    private javax.swing.JTextField TextFildInserirCpfNovoCliente;
    private javax.swing.JFormattedTextField TextFildInserirDataNascimentoNovoCliente;
    private javax.swing.JTextField TextFildInserirEnderecoNovoCliente;
    private javax.swing.JTextField TextFildInserirNomeNovoCliente;
    private javax.swing.JTextField TextFildInserirSaldoInicialContaNovoCliente;
    // End of variables declaration//GEN-END:variables
}
