/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 *
 * @author iuryi
 */
public class JFRelatorioUmCliente extends javax.swing.JFrame {
ArrayList<Cliente> ListaCliente;
    /**
     * Creates new form JFRelatorioCliente
     */

public void CarregaTabelaCliente(){
    DefaultTableModel modelo = new DefaultTableModel(new Object[]{"CPF","Nome","Sexo","Data de Nascimento","Endereço"},0);
    for(int i=0;i<ListaCliente.size();i++){
        modelo.addRow(new Object[]{ListaCliente.get(i).getCPF(),ListaCliente.get(i).getNome(),ListaCliente.get(i).getSexo(),ListaCliente.get(i).getDataNascimento(),ListaCliente.get(i).getEndereco()});
    }    
    TableRelatorioUmCliente.setModel(modelo);
    }

    public JFRelatorioUmCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextFieldInserirCpfBuscaRelatorioUmCliente = new javax.swing.JTextField();
        ButtonBuscaCpfRelatorioUmCliente = new javax.swing.JButton();
        ButtonCancelarRelatorioUmCliente = new javax.swing.JButton();
        PanelRelatorioUmCliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableRelatorioUmCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CPF:");

        TextFieldInserirCpfBuscaRelatorioUmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldInserirCpfBuscaRelatorioUmClienteActionPerformed(evt);
            }
        });

        ButtonBuscaCpfRelatorioUmCliente.setText("Buscar");
        ButtonBuscaCpfRelatorioUmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscaCpfRelatorioUmClienteActionPerformed(evt);
            }
        });

        ButtonCancelarRelatorioUmCliente.setText("Cancelar");
        ButtonCancelarRelatorioUmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarRelatorioUmClienteActionPerformed(evt);
            }
        });

        PanelRelatorioUmCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatório do Cliente"));

        TableRelatorioUmCliente.setAutoCreateRowSorter(true);
        TableRelatorioUmCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Sexo", "Data de Nascimento", "Endereço", "Conta", "N° da Conta", "Saldo da Conta"
            }
        ));
        jScrollPane1.setViewportView(TableRelatorioUmCliente);

        javax.swing.GroupLayout PanelRelatorioUmClienteLayout = new javax.swing.GroupLayout(PanelRelatorioUmCliente);
        PanelRelatorioUmCliente.setLayout(PanelRelatorioUmClienteLayout);
        PanelRelatorioUmClienteLayout.setHorizontalGroup(
            PanelRelatorioUmClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRelatorioUmClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelRelatorioUmClienteLayout.setVerticalGroup(
            PanelRelatorioUmClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRelatorioUmClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelRelatorioUmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldInserirCpfBuscaRelatorioUmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonBuscaCpfRelatorioUmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(ButtonCancelarRelatorioUmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonBuscaCpfRelatorioUmCliente)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(TextFieldInserirCpfBuscaRelatorioUmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelRelatorioUmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonCancelarRelatorioUmCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldInserirCpfBuscaRelatorioUmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldInserirCpfBuscaRelatorioUmClienteActionPerformed
        // TODO add your handling code here:
        TextFieldInserirCpfBuscaRelatorioUmCliente.getText();
    }//GEN-LAST:event_TextFieldInserirCpfBuscaRelatorioUmClienteActionPerformed

    private void ButtonBuscaCpfRelatorioUmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscaCpfRelatorioUmClienteActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<ListaCliente.size();i++){
        if(TextFieldInserirCpfBuscaRelatorioUmCliente.getText().equals(ListaCliente.get(i).getCPF())){
        CarregaTabelaCliente();    
    }   
        else{
            JOptionPane.showMessageDialog(this,"CPF não encontrado");
            TextFieldInserirCpfBuscaRelatorioUmCliente.setText("");
            
        }
        }
    }//GEN-LAST:event_ButtonBuscaCpfRelatorioUmClienteActionPerformed

    private void ButtonCancelarRelatorioUmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarRelatorioUmClienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonCancelarRelatorioUmClienteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscaCpfRelatorioUmCliente;
    private javax.swing.JButton ButtonCancelarRelatorioUmCliente;
    private javax.swing.JPanel PanelRelatorioUmCliente;
    private javax.swing.JTable TableRelatorioUmCliente;
    private javax.swing.JTextField TextFieldInserirCpfBuscaRelatorioUmCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
