/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Conta;

/**
 *
 * @author iuryi
 */
public class JFSaque extends javax.swing.JFrame {
ArrayList<Conta> Contas;
    /**
     * Creates new form JFSaque
     */
    public JFSaque() {
        initComponents();
        Contas  = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSaque = new javax.swing.JPanel();
        LabelNumContaSaque = new javax.swing.JLabel();
        TextFieldInseirirNumContaSaque = new javax.swing.JTextField();
        LabelValorSaque = new javax.swing.JLabel();
        TextFieldInserirValorSaque = new javax.swing.JTextField();
        ButtonConfirmaSaque = new javax.swing.JButton();
        ButtonCancelaSaque = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelSaque.setBorder(javax.swing.BorderFactory.createTitledBorder("Saque"));

        LabelNumContaSaque.setText("N° da Conta:");

        TextFieldInseirirNumContaSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldInseirirNumContaSaqueActionPerformed(evt);
            }
        });

        LabelValorSaque.setText("Valor do Saque:");

        TextFieldInserirValorSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldInserirValorSaqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSaqueLayout = new javax.swing.GroupLayout(PanelSaque);
        PanelSaque.setLayout(PanelSaqueLayout);
        PanelSaqueLayout.setHorizontalGroup(
            PanelSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSaqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSaqueLayout.createSequentialGroup()
                        .addComponent(LabelNumContaSaque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldInseirirNumContaSaque))
                    .addGroup(PanelSaqueLayout.createSequentialGroup()
                        .addComponent(LabelValorSaque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldInserirValorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 107, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelSaqueLayout.setVerticalGroup(
            PanelSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSaqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNumContaSaque)
                    .addComponent(TextFieldInseirirNumContaSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelValorSaque)
                    .addComponent(TextFieldInserirValorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        ButtonConfirmaSaque.setText("Confirmar");
        ButtonConfirmaSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmaSaqueActionPerformed(evt);
            }
        });

        ButtonCancelaSaque.setText("Cancelar");
        ButtonCancelaSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelaSaqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelSaque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonConfirmaSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonCancelaSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonConfirmaSaque)
                    .addComponent(ButtonCancelaSaque))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldInseirirNumContaSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldInseirirNumContaSaqueActionPerformed
        // TODO add your handling code here:
        TextFieldInseirirNumContaSaque.getText();
    }//GEN-LAST:event_TextFieldInseirirNumContaSaqueActionPerformed

    private void TextFieldInserirValorSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldInserirValorSaqueActionPerformed
        // TODO add your handling code here:
         TextFieldInserirValorSaque.getText();
    }//GEN-LAST:event_TextFieldInserirValorSaqueActionPerformed

    private void ButtonConfirmaSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmaSaqueActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<Contas.size();i++){
            if(TextFieldInseirirNumContaSaque.getText().equals(Contas.get(i).getNumero())){
            
        //    TextFieldInserirValorSaque.getText(); Precisa ser numero para subtrair da conta 
            JOptionPane.showMessageDialog(this,"Saldo transferido com sucesso.");
            TextFieldInseirirNumContaSaque.setText("");
            TextFieldInserirValorSaque.setText("");
            }
                   else{
            JOptionPane.showMessageDialog(this,"Transferencia falhou");
            TextFieldInseirirNumContaSaque.setText("");
            TextFieldInserirValorSaque.setText("");
            
        }
        }
        
    }//GEN-LAST:event_ButtonConfirmaSaqueActionPerformed

    private void ButtonCancelaSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelaSaqueActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonCancelaSaqueActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelaSaque;
    private javax.swing.JButton ButtonConfirmaSaque;
    private javax.swing.JLabel LabelNumContaSaque;
    private javax.swing.JLabel LabelValorSaque;
    private javax.swing.JPanel PanelSaque;
    private javax.swing.JTextField TextFieldInseirirNumContaSaque;
    private javax.swing.JTextField TextFieldInserirValorSaque;
    // End of variables declaration//GEN-END:variables
}
